host: https://maneger765.testrail.io
project: test
username: maneger765@huvacliq.com
key: xWg1.dMmOREKsZ6Lf1su-4RtPW3IZsh0be1OagZiU
title: MultiplicationTest.xml
run_id: 39
suite_id: 27
file: C:\Users\Hasan Abdullah\Desktop\testrail_autometed_test\report_sample\MultiplicationTest.xml
