host: https://maneger765.testrail.io
project: test
username: maneger765@huvacliq.com
title: SmokeTest.xml
run_id: 8
suite_id: 6
file: C:\Users\Hasan Abdullah\IdeaProjects\testng/report_sample/TEST-TestSuite.xml
