host: https://esteventester.testrail.io
project: test
username: atharv.esteven@foundtoo.com
key: /2HLUtQj8Lftji0KqynP-tDOf/YIPzEDaDRaPAXU6
title: MultiplicationTest.xml
run_id: 39
suite_id: 27
file: C:\Users\Hasan Abdullah\IdeaProjects\testng\report_sample\MultiplicationTest.xml
